/* start module: pyjamas.ui.Event */
$pyjs.loaded_modules['pyjamas.ui.Event'] = function (__mod_name__) {
	if($pyjs.loaded_modules['pyjamas.ui.Event'].__was_initialized__) return $pyjs.loaded_modules['pyjamas.ui.Event'];
	if(typeof $pyjs.loaded_modules['pyjamas.ui'] == 'undefined' || !$pyjs.loaded_modules['pyjamas.ui'].__was_initialized__) $p['___import___']('pyjamas.ui', null);
	var $m = $pyjs.loaded_modules["pyjamas.ui.Event"];
	$m.__repr__ = function() { return "<module: pyjamas.ui.Event>"; };
	$m.__was_initialized__ = true;
	if ((__mod_name__ === null) || (typeof __mod_name__ == 'undefined')) __mod_name__ = 'pyjamas.ui.Event';
	$m.__name__ = __mod_name__;
	$m.__track_lines__ = new Array();
	$pyjs.loaded_modules['pyjamas.ui']['Event'] = $pyjs.loaded_modules['pyjamas.ui.Event'];
	try {
		$m.__track_lines__[1] = 'pyjamas.ui.Event.py, line 1:\n    # Copyright 2006 James Tauber and contributors';
		$m.__track_lines__[20] = 'pyjamas.ui.Event.py, line 20:\n    BUTTON_LEFT   = 1';
		$m.__track_lines__[21] = 'pyjamas.ui.Event.py, line 21:\n    BUTTON_MIDDLE = 4';
		$m.__track_lines__[22] = 'pyjamas.ui.Event.py, line 22:\n    BUTTON_RIGHT  = 2';
		$m.__track_lines__[24] = 'pyjamas.ui.Event.py, line 24:\n    ONBLUR        = 0x01000';
		$m.__track_lines__[25] = 'pyjamas.ui.Event.py, line 25:\n    ONCHANGE      = 0x00400';
		$m.__track_lines__[26] = 'pyjamas.ui.Event.py, line 26:\n    ONCLICK       = 0x00001';
		$m.__track_lines__[27] = 'pyjamas.ui.Event.py, line 27:\n    ONCONTEXTMENU = 0x20000';
		$m.__track_lines__[28] = 'pyjamas.ui.Event.py, line 28:\n    ONDBLCLICK    = 0x00002';
		$m.__track_lines__[29] = 'pyjamas.ui.Event.py, line 29:\n    ONERROR       = 0x10000';
		$m.__track_lines__[30] = 'pyjamas.ui.Event.py, line 30:\n    ONFOCUS       = 0x00800';
		$m.__track_lines__[31] = 'pyjamas.ui.Event.py, line 31:\n    ONKEYDOWN     = 0x00080';
		$m.__track_lines__[32] = 'pyjamas.ui.Event.py, line 32:\n    ONKEYPRESS    = 0x00100';
		$m.__track_lines__[33] = 'pyjamas.ui.Event.py, line 33:\n    ONKEYUP       = 0x00200';
		$m.__track_lines__[34] = 'pyjamas.ui.Event.py, line 34:\n    ONLOAD        = 0x08000';
		$m.__track_lines__[35] = 'pyjamas.ui.Event.py, line 35:\n    ONLOSECAPTURE = 0x02000';
		$m.__track_lines__[36] = 'pyjamas.ui.Event.py, line 36:\n    ONMOUSEDOWN   = 0x00004';
		$m.__track_lines__[37] = 'pyjamas.ui.Event.py, line 37:\n    ONMOUSEMOVE   = 0x00040';
		$m.__track_lines__[38] = 'pyjamas.ui.Event.py, line 38:\n    ONMOUSEOUT    = 0x00020';
		$m.__track_lines__[39] = 'pyjamas.ui.Event.py, line 39:\n    ONMOUSEOVER   = 0x00010';
		$m.__track_lines__[40] = 'pyjamas.ui.Event.py, line 40:\n    ONMOUSEUP     = 0x00008';
		$m.__track_lines__[41] = 'pyjamas.ui.Event.py, line 41:\n    ONMOUSEWHEEL  = 0x40000';
		$m.__track_lines__[42] = 'pyjamas.ui.Event.py, line 42:\n    ONSCROLL      = 0x04000';
		$m.__track_lines__[43] = 'pyjamas.ui.Event.py, line 43:\n    ONINPUT       = 0x80000';
		$m.__track_lines__[44] = 'pyjamas.ui.Event.py, line 44:\n    DRAGEVENTS    = 0x100000';
		$m.__track_lines__[45] = 'pyjamas.ui.Event.py, line 45:\n    DROPEVENTS    = 0x200000';
		$m.__track_lines__[47] = 'pyjamas.ui.Event.py, line 47:\n    FOCUSEVENTS   = 0x01800 # ONFOCUS | ONBLUR';
		$m.__track_lines__[48] = 'pyjamas.ui.Event.py, line 48:\n    KEYEVENTS     = 0x00380 # ONKEYDOWN | ONKEYPRESS | ONKEYUP';
		$m.__track_lines__[49] = 'pyjamas.ui.Event.py, line 49:\n    MOUSEEVENTS   = 0x0007C # ONMOUSEDOWN | ONMOUSEUP | ONMOUSEMOVE | ONMOUSEOVER | ONMOUSEOUT';
		$m.__track_lines__[51] = 'pyjamas.ui.Event.py, line 51:\n    eventbits = {';
		$m.__track_lines__[79] = 'pyjamas.ui.Event.py, line 79:\n    eventmap = {';
		$m.__track_lines__[87] = 'pyjamas.ui.Event.py, line 87:\n    def _create_eventmap():';
		$m.__track_lines__[88] = 'pyjamas.ui.Event.py, line 88:\n    for bit, bitmap in eventbits.iteritems():';
		$m.__track_lines__[89] = 'pyjamas.ui.Event.py, line 89:\n    eventmap[bitmap[0]] = bit';
		$m.__track_lines__[91] = 'pyjamas.ui.Event.py, line 91:\n    def init():';
		$m.__track_lines__[92] = 'pyjamas.ui.Event.py, line 92:\n    _create_eventmap()';
		$m.__track_lines__[94] = 'pyjamas.ui.Event.py, line 94:\n    init()';

		var $constant_int_4096 = new $p['int'](4096);
		var $constant_int_1 = new $p['int'](1);
		var $constant_int_2 = new $p['int'](2);
		var $constant_int_4 = new $p['int'](4);
		var $constant_int_8192 = new $p['int'](8192);
		var $constant_int_8 = new $p['int'](8);
		var $constant_int_128 = new $p['int'](128);
		var $constant_int_256 = new $p['int'](256);
		var $constant_int_16 = new $p['int'](16);
		var $constant_int_512 = new $p['int'](512);
		var $constant_int_0 = new $p['int'](0);
		var $constant_int_524288 = new $p['int'](524288);
		var $constant_int_32 = new $p['int'](32);
		var $constant_int_131072 = new $p['int'](131072);
		var $constant_int_896 = new $p['int'](896);
		var $constant_int_262144 = new $p['int'](262144);
		var $constant_int_1024 = new $p['int'](1024);
		var $constant_int_16384 = new $p['int'](16384);
		var $constant_int_1048576 = new $p['int'](1048576);
		var $constant_int_32768 = new $p['int'](32768);
		var $constant_int_64 = new $p['int'](64);
		var $constant_int_2048 = new $p['int'](2048);
		var $constant_int_2097152 = new $p['int'](2097152);
		var $constant_int_65536 = new $p['int'](65536);
		var $constant_int_6144 = new $p['int'](6144);
		var $constant_int_124 = new $p['int'](124);
		$pyjs.track.module='pyjamas.ui.Event';
		$pyjs.track.lineno=1;
		$pyjs.track.lineno=20;
		$m['BUTTON_LEFT'] = $constant_int_1;
		$pyjs.track.lineno=21;
		$m['BUTTON_MIDDLE'] = $constant_int_4;
		$pyjs.track.lineno=22;
		$m['BUTTON_RIGHT'] = $constant_int_2;
		$pyjs.track.lineno=24;
		$m['ONBLUR'] = $constant_int_4096;
		$pyjs.track.lineno=25;
		$m['ONCHANGE'] = $constant_int_1024;
		$pyjs.track.lineno=26;
		$m['ONCLICK'] = $constant_int_1;
		$pyjs.track.lineno=27;
		$m['ONCONTEXTMENU'] = $constant_int_131072;
		$pyjs.track.lineno=28;
		$m['ONDBLCLICK'] = $constant_int_2;
		$pyjs.track.lineno=29;
		$m['ONERROR'] = $constant_int_65536;
		$pyjs.track.lineno=30;
		$m['ONFOCUS'] = $constant_int_2048;
		$pyjs.track.lineno=31;
		$m['ONKEYDOWN'] = $constant_int_128;
		$pyjs.track.lineno=32;
		$m['ONKEYPRESS'] = $constant_int_256;
		$pyjs.track.lineno=33;
		$m['ONKEYUP'] = $constant_int_512;
		$pyjs.track.lineno=34;
		$m['ONLOAD'] = $constant_int_32768;
		$pyjs.track.lineno=35;
		$m['ONLOSECAPTURE'] = $constant_int_8192;
		$pyjs.track.lineno=36;
		$m['ONMOUSEDOWN'] = $constant_int_4;
		$pyjs.track.lineno=37;
		$m['ONMOUSEMOVE'] = $constant_int_64;
		$pyjs.track.lineno=38;
		$m['ONMOUSEOUT'] = $constant_int_32;
		$pyjs.track.lineno=39;
		$m['ONMOUSEOVER'] = $constant_int_16;
		$pyjs.track.lineno=40;
		$m['ONMOUSEUP'] = $constant_int_8;
		$pyjs.track.lineno=41;
		$m['ONMOUSEWHEEL'] = $constant_int_262144;
		$pyjs.track.lineno=42;
		$m['ONSCROLL'] = $constant_int_16384;
		$pyjs.track.lineno=43;
		$m['ONINPUT'] = $constant_int_524288;
		$pyjs.track.lineno=44;
		$m['DRAGEVENTS'] = $constant_int_1048576;
		$pyjs.track.lineno=45;
		$m['DROPEVENTS'] = $constant_int_2097152;
		$pyjs.track.lineno=47;
		$m['FOCUSEVENTS'] = $constant_int_6144;
		$pyjs.track.lineno=48;
		$m['KEYEVENTS'] = $constant_int_896;
		$pyjs.track.lineno=49;
		$m['MOUSEEVENTS'] = $constant_int_124;
		$pyjs.track.lineno=51;
		$m['eventbits'] = (function(){try{try{$pyjs.in_try_except += 1;
		return $p['dict']([[$constant_int_1, (function(){try{try{$pyjs.in_try_except += 1;
		return $p['tuple'](['click', (function(){try{try{$pyjs.in_try_except += 1;
		return $p['list'](['click']);
}finally{$pyjs.in_try_except-=1;}}catch($pyjs_dbg_1_err){if (!$p['isinstance']($pyjs_dbg_1_err, $p['StopIteration'])){$p['_handle_exception']($pyjs_dbg_1_err);}throw $pyjs_dbg_1_err;
}})()]);
}finally{$pyjs.in_try_except-=1;}}catch($pyjs_dbg_2_err){if (!$p['isinstance']($pyjs_dbg_2_err, $p['StopIteration'])){$p['_handle_exception']($pyjs_dbg_2_err);}throw $pyjs_dbg_2_err;
}})()], [$constant_int_2, (function(){try{try{$pyjs.in_try_except += 1;
		return $p['tuple'](['dblclick', (function(){try{try{$pyjs.in_try_except += 1;
		return $p['list'](['dblclick']);
}finally{$pyjs.in_try_except-=1;}}catch($pyjs_dbg_3_err){if (!$p['isinstance']($pyjs_dbg_3_err, $p['StopIteration'])){$p['_handle_exception']($pyjs_dbg_3_err);}throw $pyjs_dbg_3_err;
}})()]);
}finally{$pyjs.in_try_except-=1;}}catch($pyjs_dbg_4_err){if (!$p['isinstance']($pyjs_dbg_4_err, $p['StopIteration'])){$p['_handle_exception']($pyjs_dbg_4_err);}throw $pyjs_dbg_4_err;
}})()], [$constant_int_4, (function(){try{try{$pyjs.in_try_except += 1;
		return $p['tuple'](['mousedown', (function(){try{try{$pyjs.in_try_except += 1;
		return $p['list'](['mousedown']);
}finally{$pyjs.in_try_except-=1;}}catch($pyjs_dbg_5_err){if (!$p['isinstance']($pyjs_dbg_5_err, $p['StopIteration'])){$p['_handle_exception']($pyjs_dbg_5_err);}throw $pyjs_dbg_5_err;
}})()]);
}finally{$pyjs.in_try_except-=1;}}catch($pyjs_dbg_6_err){if (!$p['isinstance']($pyjs_dbg_6_err, $p['StopIteration'])){$p['_handle_exception']($pyjs_dbg_6_err);}throw $pyjs_dbg_6_err;
}})()], [$constant_int_8, (function(){try{try{$pyjs.in_try_except += 1;
		return $p['tuple'](['mouseup', (function(){try{try{$pyjs.in_try_except += 1;
		return $p['list'](['mouseup']);
}finally{$pyjs.in_try_except-=1;}}catch($pyjs_dbg_7_err){if (!$p['isinstance']($pyjs_dbg_7_err, $p['StopIteration'])){$p['_handle_exception']($pyjs_dbg_7_err);}throw $pyjs_dbg_7_err;
}})()]);
}finally{$pyjs.in_try_except-=1;}}catch($pyjs_dbg_8_err){if (!$p['isinstance']($pyjs_dbg_8_err, $p['StopIteration'])){$p['_handle_exception']($pyjs_dbg_8_err);}throw $pyjs_dbg_8_err;
}})()], [$constant_int_16, (function(){try{try{$pyjs.in_try_except += 1;
		return $p['tuple'](['mouseover', (function(){try{try{$pyjs.in_try_except += 1;
		return $p['list'](['mouseover']);
}finally{$pyjs.in_try_except-=1;}}catch($pyjs_dbg_9_err){if (!$p['isinstance']($pyjs_dbg_9_err, $p['StopIteration'])){$p['_handle_exception']($pyjs_dbg_9_err);}throw $pyjs_dbg_9_err;
}})()]);
}finally{$pyjs.in_try_except-=1;}}catch($pyjs_dbg_10_err){if (!$p['isinstance']($pyjs_dbg_10_err, $p['StopIteration'])){$p['_handle_exception']($pyjs_dbg_10_err);}throw $pyjs_dbg_10_err;
}})()], [$constant_int_32, (function(){try{try{$pyjs.in_try_except += 1;
		return $p['tuple'](['mouseout', (function(){try{try{$pyjs.in_try_except += 1;
		return $p['list'](['mouseout']);
}finally{$pyjs.in_try_except-=1;}}catch($pyjs_dbg_11_err){if (!$p['isinstance']($pyjs_dbg_11_err, $p['StopIteration'])){$p['_handle_exception']($pyjs_dbg_11_err);}throw $pyjs_dbg_11_err;
}})()]);
}finally{$pyjs.in_try_except-=1;}}catch($pyjs_dbg_12_err){if (!$p['isinstance']($pyjs_dbg_12_err, $p['StopIteration'])){$p['_handle_exception']($pyjs_dbg_12_err);}throw $pyjs_dbg_12_err;
}})()], [$constant_int_64, (function(){try{try{$pyjs.in_try_except += 1;
		return $p['tuple'](['mousemove', (function(){try{try{$pyjs.in_try_except += 1;
		return $p['list'](['mousemove']);
}finally{$pyjs.in_try_except-=1;}}catch($pyjs_dbg_13_err){if (!$p['isinstance']($pyjs_dbg_13_err, $p['StopIteration'])){$p['_handle_exception']($pyjs_dbg_13_err);}throw $pyjs_dbg_13_err;
}})()]);
}finally{$pyjs.in_try_except-=1;}}catch($pyjs_dbg_14_err){if (!$p['isinstance']($pyjs_dbg_14_err, $p['StopIteration'])){$p['_handle_exception']($pyjs_dbg_14_err);}throw $pyjs_dbg_14_err;
}})()], [$constant_int_128, (function(){try{try{$pyjs.in_try_except += 1;
		return $p['tuple'](['keydown', (function(){try{try{$pyjs.in_try_except += 1;
		return $p['list'](['keydown']);
}finally{$pyjs.in_try_except-=1;}}catch($pyjs_dbg_15_err){if (!$p['isinstance']($pyjs_dbg_15_err, $p['StopIteration'])){$p['_handle_exception']($pyjs_dbg_15_err);}throw $pyjs_dbg_15_err;
}})()]);
}finally{$pyjs.in_try_except-=1;}}catch($pyjs_dbg_16_err){if (!$p['isinstance']($pyjs_dbg_16_err, $p['StopIteration'])){$p['_handle_exception']($pyjs_dbg_16_err);}throw $pyjs_dbg_16_err;
}})()], [$constant_int_256, (function(){try{try{$pyjs.in_try_except += 1;
		return $p['tuple'](['keypress', (function(){try{try{$pyjs.in_try_except += 1;
		return $p['list'](['keypress']);
}finally{$pyjs.in_try_except-=1;}}catch($pyjs_dbg_17_err){if (!$p['isinstance']($pyjs_dbg_17_err, $p['StopIteration'])){$p['_handle_exception']($pyjs_dbg_17_err);}throw $pyjs_dbg_17_err;
}})()]);
}finally{$pyjs.in_try_except-=1;}}catch($pyjs_dbg_18_err){if (!$p['isinstance']($pyjs_dbg_18_err, $p['StopIteration'])){$p['_handle_exception']($pyjs_dbg_18_err);}throw $pyjs_dbg_18_err;
}})()], [$constant_int_512, (function(){try{try{$pyjs.in_try_except += 1;
		return $p['tuple'](['keyup', (function(){try{try{$pyjs.in_try_except += 1;
		return $p['list'](['keyup']);
}finally{$pyjs.in_try_except-=1;}}catch($pyjs_dbg_19_err){if (!$p['isinstance']($pyjs_dbg_19_err, $p['StopIteration'])){$p['_handle_exception']($pyjs_dbg_19_err);}throw $pyjs_dbg_19_err;
}})()]);
}finally{$pyjs.in_try_except-=1;}}catch($pyjs_dbg_20_err){if (!$p['isinstance']($pyjs_dbg_20_err, $p['StopIteration'])){$p['_handle_exception']($pyjs_dbg_20_err);}throw $pyjs_dbg_20_err;
}})()], [$constant_int_1024, (function(){try{try{$pyjs.in_try_except += 1;
		return $p['tuple'](['change', (function(){try{try{$pyjs.in_try_except += 1;
		return $p['list'](['change']);
}finally{$pyjs.in_try_except-=1;}}catch($pyjs_dbg_21_err){if (!$p['isinstance']($pyjs_dbg_21_err, $p['StopIteration'])){$p['_handle_exception']($pyjs_dbg_21_err);}throw $pyjs_dbg_21_err;
}})()]);
}finally{$pyjs.in_try_except-=1;}}catch($pyjs_dbg_22_err){if (!$p['isinstance']($pyjs_dbg_22_err, $p['StopIteration'])){$p['_handle_exception']($pyjs_dbg_22_err);}throw $pyjs_dbg_22_err;
}})()], [$constant_int_2048, (function(){try{try{$pyjs.in_try_except += 1;
		return $p['tuple'](['focus', (function(){try{try{$pyjs.in_try_except += 1;
		return $p['list'](['focus']);
}finally{$pyjs.in_try_except-=1;}}catch($pyjs_dbg_23_err){if (!$p['isinstance']($pyjs_dbg_23_err, $p['StopIteration'])){$p['_handle_exception']($pyjs_dbg_23_err);}throw $pyjs_dbg_23_err;
}})()]);
}finally{$pyjs.in_try_except-=1;}}catch($pyjs_dbg_24_err){if (!$p['isinstance']($pyjs_dbg_24_err, $p['StopIteration'])){$p['_handle_exception']($pyjs_dbg_24_err);}throw $pyjs_dbg_24_err;
}})()], [$constant_int_4096, (function(){try{try{$pyjs.in_try_except += 1;
		return $p['tuple'](['blur', (function(){try{try{$pyjs.in_try_except += 1;
		return $p['list'](['blur']);
}finally{$pyjs.in_try_except-=1;}}catch($pyjs_dbg_25_err){if (!$p['isinstance']($pyjs_dbg_25_err, $p['StopIteration'])){$p['_handle_exception']($pyjs_dbg_25_err);}throw $pyjs_dbg_25_err;
}})()]);
}finally{$pyjs.in_try_except-=1;}}catch($pyjs_dbg_26_err){if (!$p['isinstance']($pyjs_dbg_26_err, $p['StopIteration'])){$p['_handle_exception']($pyjs_dbg_26_err);}throw $pyjs_dbg_26_err;
}})()], [$constant_int_8192, (function(){try{try{$pyjs.in_try_except += 1;
		return $p['tuple'](['losecapture', (function(){try{try{$pyjs.in_try_except += 1;
		return $p['list'](['losecapture']);
}finally{$pyjs.in_try_except-=1;}}catch($pyjs_dbg_27_err){if (!$p['isinstance']($pyjs_dbg_27_err, $p['StopIteration'])){$p['_handle_exception']($pyjs_dbg_27_err);}throw $pyjs_dbg_27_err;
}})()]);
}finally{$pyjs.in_try_except-=1;}}catch($pyjs_dbg_28_err){if (!$p['isinstance']($pyjs_dbg_28_err, $p['StopIteration'])){$p['_handle_exception']($pyjs_dbg_28_err);}throw $pyjs_dbg_28_err;
}})()], [$constant_int_16384, (function(){try{try{$pyjs.in_try_except += 1;
		return $p['tuple'](['scroll', (function(){try{try{$pyjs.in_try_except += 1;
		return $p['list'](['scroll']);
}finally{$pyjs.in_try_except-=1;}}catch($pyjs_dbg_29_err){if (!$p['isinstance']($pyjs_dbg_29_err, $p['StopIteration'])){$p['_handle_exception']($pyjs_dbg_29_err);}throw $pyjs_dbg_29_err;
}})()]);
}finally{$pyjs.in_try_except-=1;}}catch($pyjs_dbg_30_err){if (!$p['isinstance']($pyjs_dbg_30_err, $p['StopIteration'])){$p['_handle_exception']($pyjs_dbg_30_err);}throw $pyjs_dbg_30_err;
}})()], [$constant_int_32768, (function(){try{try{$pyjs.in_try_except += 1;
		return $p['tuple'](['load', (function(){try{try{$pyjs.in_try_except += 1;
		return $p['list'](['load']);
}finally{$pyjs.in_try_except-=1;}}catch($pyjs_dbg_31_err){if (!$p['isinstance']($pyjs_dbg_31_err, $p['StopIteration'])){$p['_handle_exception']($pyjs_dbg_31_err);}throw $pyjs_dbg_31_err;
}})()]);
}finally{$pyjs.in_try_except-=1;}}catch($pyjs_dbg_32_err){if (!$p['isinstance']($pyjs_dbg_32_err, $p['StopIteration'])){$p['_handle_exception']($pyjs_dbg_32_err);}throw $pyjs_dbg_32_err;
}})()], [$constant_int_65536, (function(){try{try{$pyjs.in_try_except += 1;
		return $p['tuple'](['error', (function(){try{try{$pyjs.in_try_except += 1;
		return $p['list'](['error']);
}finally{$pyjs.in_try_except-=1;}}catch($pyjs_dbg_33_err){if (!$p['isinstance']($pyjs_dbg_33_err, $p['StopIteration'])){$p['_handle_exception']($pyjs_dbg_33_err);}throw $pyjs_dbg_33_err;
}})()]);
}finally{$pyjs.in_try_except-=1;}}catch($pyjs_dbg_34_err){if (!$p['isinstance']($pyjs_dbg_34_err, $p['StopIteration'])){$p['_handle_exception']($pyjs_dbg_34_err);}throw $pyjs_dbg_34_err;
}})()], [$constant_int_131072, (function(){try{try{$pyjs.in_try_except += 1;
		return $p['tuple'](['contextmenu', (function(){try{try{$pyjs.in_try_except += 1;
		return $p['list'](['contextmenu']);
}finally{$pyjs.in_try_except-=1;}}catch($pyjs_dbg_35_err){if (!$p['isinstance']($pyjs_dbg_35_err, $p['StopIteration'])){$p['_handle_exception']($pyjs_dbg_35_err);}throw $pyjs_dbg_35_err;
}})()]);
}finally{$pyjs.in_try_except-=1;}}catch($pyjs_dbg_36_err){if (!$p['isinstance']($pyjs_dbg_36_err, $p['StopIteration'])){$p['_handle_exception']($pyjs_dbg_36_err);}throw $pyjs_dbg_36_err;
}})()], [$constant_int_262144, (function(){try{try{$pyjs.in_try_except += 1;
		return $p['tuple'](['mousewheel', (function(){try{try{$pyjs.in_try_except += 1;
		return $p['list'](['mousewheel']);
}finally{$pyjs.in_try_except-=1;}}catch($pyjs_dbg_37_err){if (!$p['isinstance']($pyjs_dbg_37_err, $p['StopIteration'])){$p['_handle_exception']($pyjs_dbg_37_err);}throw $pyjs_dbg_37_err;
}})()]);
}finally{$pyjs.in_try_except-=1;}}catch($pyjs_dbg_38_err){if (!$p['isinstance']($pyjs_dbg_38_err, $p['StopIteration'])){$p['_handle_exception']($pyjs_dbg_38_err);}throw $pyjs_dbg_38_err;
}})()], [$constant_int_524288, (function(){try{try{$pyjs.in_try_except += 1;
		return $p['tuple'](['input', (function(){try{try{$pyjs.in_try_except += 1;
		return $p['list'](['input']);
}finally{$pyjs.in_try_except-=1;}}catch($pyjs_dbg_39_err){if (!$p['isinstance']($pyjs_dbg_39_err, $p['StopIteration'])){$p['_handle_exception']($pyjs_dbg_39_err);}throw $pyjs_dbg_39_err;
}})()]);
}finally{$pyjs.in_try_except-=1;}}catch($pyjs_dbg_40_err){if (!$p['isinstance']($pyjs_dbg_40_err, $p['StopIteration'])){$p['_handle_exception']($pyjs_dbg_40_err);}throw $pyjs_dbg_40_err;
}})()], [$constant_int_1048576, (function(){try{try{$pyjs.in_try_except += 1;
		return $p['tuple'](['dragevents', (function(){try{try{$pyjs.in_try_except += 1;
		return $p['list'](['drag', 'dragstart', 'dragend']);
}finally{$pyjs.in_try_except-=1;}}catch($pyjs_dbg_41_err){if (!$p['isinstance']($pyjs_dbg_41_err, $p['StopIteration'])){$p['_handle_exception']($pyjs_dbg_41_err);}throw $pyjs_dbg_41_err;
}})()]);
}finally{$pyjs.in_try_except-=1;}}catch($pyjs_dbg_42_err){if (!$p['isinstance']($pyjs_dbg_42_err, $p['StopIteration'])){$p['_handle_exception']($pyjs_dbg_42_err);}throw $pyjs_dbg_42_err;
}})()], [$constant_int_2097152, (function(){try{try{$pyjs.in_try_except += 1;
		return $p['tuple'](['dropevents', (function(){try{try{$pyjs.in_try_except += 1;
		return $p['list'](['drop', 'dragenter', 'dragover', 'dragleave']);
}finally{$pyjs.in_try_except-=1;}}catch($pyjs_dbg_43_err){if (!$p['isinstance']($pyjs_dbg_43_err, $p['StopIteration'])){$p['_handle_exception']($pyjs_dbg_43_err);}throw $pyjs_dbg_43_err;
}})()]);
}finally{$pyjs.in_try_except-=1;}}catch($pyjs_dbg_44_err){if (!$p['isinstance']($pyjs_dbg_44_err, $p['StopIteration'])){$p['_handle_exception']($pyjs_dbg_44_err);}throw $pyjs_dbg_44_err;
}})()]]);
}finally{$pyjs.in_try_except-=1;}}catch($pyjs_dbg_45_err){if (!$p['isinstance']($pyjs_dbg_45_err, $p['StopIteration'])){$p['_handle_exception']($pyjs_dbg_45_err);}throw $pyjs_dbg_45_err;
}})();
		$pyjs.track.lineno=79;
		$m['eventmap'] = (function(){try{try{$pyjs.in_try_except += 1;
		return $p['dict']([['mousewheel', $constant_int_262144], ['mousescroll', $constant_int_262144], ['DOMMouseScroll', $constant_int_262144], ['input', $constant_int_524288], ['propertychange', $constant_int_524288]]);
}finally{$pyjs.in_try_except-=1;}}catch($pyjs_dbg_46_err){if (!$p['isinstance']($pyjs_dbg_46_err, $p['StopIteration'])){$p['_handle_exception']($pyjs_dbg_46_err);}throw $pyjs_dbg_46_err;
}})();
		$pyjs.track.lineno=87;
		$m['_create_eventmap'] = function() {
			if ($pyjs.options.arg_count && arguments.length != 0) $pyjs__exception_func_param(arguments.callee.__name__, 0, 0, arguments.length);
			var $iter1_nextval,$iter1_type,$iter1_iter,$iter1_array,$pyjs__trackstack_size_1,bit,bitmap,$iter1_idx;
			$pyjs.track={module:'pyjamas.ui.Event',lineno:87};$pyjs.trackstack.push($pyjs.track);
			$pyjs.track.module='pyjamas.ui.Event';
			$pyjs.track.lineno=87;
			$pyjs.track.lineno=88;
			$pyjs__trackstack_size_1=$pyjs.trackstack.length;
			$iter1_iter = (function(){try{try{$pyjs.in_try_except += 1;
			return (function(){try{try{$pyjs.in_try_except += 1;
			return $m['eventbits']['iteritems']();
}finally{$pyjs.in_try_except-=1;}}catch($pyjs_dbg_48_err){if (!$p['isinstance']($pyjs_dbg_48_err, $p['StopIteration'])){$p['_handle_exception']($pyjs_dbg_48_err);}throw $pyjs_dbg_48_err;
}})();
}finally{$pyjs.in_try_except-=1;}}catch($pyjs_dbg_49_err){if (!$p['isinstance']($pyjs_dbg_49_err, $p['StopIteration'])){$p['_handle_exception']($pyjs_dbg_49_err);}throw $pyjs_dbg_49_err;
}})();
			$iter1_nextval=$p['__iter_prepare']($iter1_iter,false);
			while (typeof($p['__wrapped_next']($iter1_nextval).$nextval) != 'undefined') {
				var $tupleassign1 = (function(){try{try{$pyjs.in_try_except += 1;
			return $p['__ass_unpack']($iter1_nextval.$nextval, 2, null);
}finally{$pyjs.in_try_except-=1;}}catch($pyjs_dbg_47_err){if (!$p['isinstance']($pyjs_dbg_47_err, $p['StopIteration'])){$p['_handle_exception']($pyjs_dbg_47_err);}throw $pyjs_dbg_47_err;
}})();
				bit = $tupleassign1[0];
				bitmap = $tupleassign1[1];
				$pyjs.track.lineno=89;
				(function(){try{try{$pyjs.in_try_except += 1;
				return $m['eventmap'].__setitem__(bitmap.__getitem__($constant_int_0), bit);
}finally{$pyjs.in_try_except-=1;}}catch($pyjs_dbg_50_err){if (!$p['isinstance']($pyjs_dbg_50_err, $p['StopIteration'])){$p['_handle_exception']($pyjs_dbg_50_err);}throw $pyjs_dbg_50_err;
}})();
			}
			if ($pyjs.trackstack.length > $pyjs__trackstack_size_1) {
				$pyjs.trackstack = $pyjs.trackstack.slice(0,$pyjs__trackstack_size_1);
				$pyjs.track = $pyjs.trackstack.slice(-1)[0];
			}
			$pyjs.track.module='pyjamas.ui.Event';
			$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);
			return null;
		};
		$m['_create_eventmap'].__name__ = '_create_eventmap';

		$m['_create_eventmap'].__bind_type__ = 0;
		$m['_create_eventmap'].__args__ = [null,null];
		$pyjs.track.lineno=91;
		$m['init'] = function() {
			if ($pyjs.options.arg_count && arguments.length != 0) $pyjs__exception_func_param(arguments.callee.__name__, 0, 0, arguments.length);

			$pyjs.track={module:'pyjamas.ui.Event',lineno:91};$pyjs.trackstack.push($pyjs.track);
			$pyjs.track.module='pyjamas.ui.Event';
			$pyjs.track.lineno=91;
			$pyjs.track.lineno=92;
			(function(){try{try{$pyjs.in_try_except += 1;
			return $m['_create_eventmap']();
}finally{$pyjs.in_try_except-=1;}}catch($pyjs_dbg_51_err){if (!$p['isinstance']($pyjs_dbg_51_err, $p['StopIteration'])){$p['_handle_exception']($pyjs_dbg_51_err);}throw $pyjs_dbg_51_err;
}})();
			$pyjs.trackstack.pop();$pyjs.track=$pyjs.trackstack.pop();$pyjs.trackstack.push($pyjs.track);
			return null;
		};
		$m['init'].__name__ = 'init';

		$m['init'].__bind_type__ = 0;
		$m['init'].__args__ = [null,null];
		$pyjs.track.lineno=94;
		(function(){try{try{$pyjs.in_try_except += 1;
		return $m['init']();
}finally{$pyjs.in_try_except-=1;}}catch($pyjs_dbg_52_err){if (!$p['isinstance']($pyjs_dbg_52_err, $p['StopIteration'])){$p['_handle_exception']($pyjs_dbg_52_err);}throw $pyjs_dbg_52_err;
}})();
	} catch ($pyjs_attr_err) {throw $p['_errorMapping']($pyjs_attr_err);};
	return this;
}; /* end pyjamas.ui.Event */


/* end module: pyjamas.ui.Event */


